spring:
  datasource:
    driver-class-name: \${FA_DB_DRIVER}
    url: \${FA_DB_URL}
    username: \${FA_DB_USER}
    password: \${FA_DB_PASSWORD}
    test-on-borrow: true
    validation-query: SELECT 1
    validation-interval: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    transaction-timeout: 1000
    hibernate:
        ddl-auto: validate

flyway:
  enabled: true
  sql-migration-suffix: .sql
  sql-migration-prefix: V
  baselineOnMigrate: true