version: '3.2'
services:
  falcontest:
    image: falconiotest/io.falcon.falcontest
    hostname: falcontest
    domainname: docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
  mysql:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3306:3306"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: test_pass
      MYSQL_DATABASE: falcondb
      MYSQL_USER: falcon_usr
      MYSQL_PASS: Db12PwD
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./mysql-init.d:/docker-entrypoint-initdb.d
  redis:
    image: redis:3.0.3
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    depends_on:
      - mysql
volumes:
  my-datavolume: